services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - src/main/resources/.env

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: med
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
